// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreServices.Api.Book.Persistence;

namespace StoreServices.Api.Book.Migrations
{
    [DbContext(typeof(ContextBook))]
    [Migration("20220208133800_MigrationsBookInitial")]
    partial class MigrationsBookInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StoreServices.Api.Book.Models.MaterialLibrary", b =>
                {
                    b.Property<Guid?>("MaterialLibraryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookAuthor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookTittle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DatePublish")
                        .HasColumnType("datetime2");

                    b.HasKey("MaterialLibraryID");

                    b.ToTable("MaterialLibrary");
                });
#pragma warning restore 612, 618
        }
    }
}
