// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreServices.Api.ShoppingCart.Persistence;

namespace StoreServices.Api.ShoppingCart.Migrations
{
    [DbContext(typeof(ContextShoppingCart))]
    partial class ContextShoppingCartModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StoreServices.Api.ShoppingCart.Models.CartSession", b =>
                {
                    b.Property<long?>("CartSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CartSessionID");

                    b.ToTable("CartSession");
                });

            modelBuilder.Entity("StoreServices.Api.ShoppingCart.Models.CartSessionDetail", b =>
                {
                    b.Property<long?>("CartSessionDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CartSessionID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductSelected")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CartSessionDetailID");

                    b.HasIndex("CartSessionID");

                    b.ToTable("CartSessionDetail");
                });

            modelBuilder.Entity("StoreServices.Api.ShoppingCart.Models.CartSessionDetail", b =>
                {
                    b.HasOne("StoreServices.Api.ShoppingCart.Models.CartSession", "CartSession")
                        .WithMany("ListDetail")
                        .HasForeignKey("CartSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
